# Generated by Django 4.0.1 on 2022-03-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restauras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Restaura',
                'verbose_name_plural': 'Restauras',
                'managed': False,
            },
        ),
    ]
