# Generated by Django 3.2.7 on 2021-11-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escriba el nombre del dominio.', max_length=20)),
                ('prefijo', models.CharField(help_text='Escriba el prefijo.', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('prefijo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('nombre', models.CharField(help_text='Escriba el nombre.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=15)),
                ('interno', models.BooleanField()),
                ('local', models.CharField(max_length=1)),
                ('estante', models.CharField(max_length=10)),
                ('grupo', models.CharField(choices=[('WI', 'Wintec'), ('SE', 'Sentai'), ('SI', 'Silver'), ('DW', 'DataWarehouse'), ('LN', 'LotusNotes'), ('SO', 'Soptec'), ('IC', 'ICE')], max_length=2)),
                ('os', models.CharField(choices=[('W', 'Windows'), ('M', 'MacOS'), ('L', 'Linux')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('nombre', models.CharField(help_text='Escriba el nombre.', max_length=50)),
                ('provincia', models.ForeignKey(help_text='Escriba la provincia a la que pertenece.', on_delete=django.db.models.deletion.PROTECT, related_name='municipio_provincia', to='nomencladores.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escriba el nombre.', max_length=20)),
                ('apellido', models.CharField(help_text='Escriba los apellidos.', max_length=40)),
                ('prefijo', models.CharField(max_length=10)),
                ('telefono', models.CharField(help_text='Escriba el número telefónico.', max_length=8)),
                ('de_cimex', models.BooleanField()),
                ('nombre_jefe_informatico', models.CharField(help_text='Escriba el nombre del jefe informático.', max_length=20)),
                ('apellido_jefe_informatico', models.CharField(help_text='Escriba el apellido del jefe informático.', max_length=40)),
                ('nombre_admin_redes', models.CharField(max_length=20)),
                ('apellido_admin_redes', models.CharField(max_length=40)),
                ('rango_inicial_ip', models.CharField(max_length=15)),
                ('rango_final_ip', models.CharField(max_length=15)),
                ('municipio', models.ForeignKey(help_text='Escoja el municipio.', on_delete=django.db.models.deletion.PROTECT, to='nomencladores.municipio')),
                ('provincia', models.ForeignKey(help_text='Escoja la provincia.', on_delete=django.db.models.deletion.PROTECT, to='nomencladores.provincia')),
            ],
        ),
    ]
