# Generated by Django 3.2.7 on 2021-11-23 21:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0002_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='apellido_admin_redes',
            field=models.CharField(help_text='Escriba el apellido del administrador de redes.', max_length=40),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre_admin_redes',
            field=models.CharField(help_text='Escriba el nombre del administrador de redes.', max_length=20),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='rango_final_ip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='rango_inicial_ip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
