# Generated by Django 3.2.7 on 2021-12-01 22:44

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0003_auto_20211123_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='apellido_admin_redes',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='apellido_jefe_informatico',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.municipio'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre_admin_redes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre_jefe_informatico',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.provincia'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='provincia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='provincia', chained_model_field='provincia', on_delete=django.db.models.deletion.CASCADE, to='nomencladores.provincia'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
