# Generated by Django 3.2.7 on 2021-12-01 22:52

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0004_auto_20211201_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='provincia', chained_model_field='provincia', on_delete=django.db.models.deletion.CASCADE, to='nomencladores.municipio'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.provincia'),
        ),
    ]
