# Generated by Django 3.2.7 on 2021-12-06 20:19

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('musi', '0004_auto_20211206_1519'),
        ('nomencladores', '0005_auto_20211201_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dominio',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='provincia', chained_model_field='provincia', on_delete=django.db.models.deletion.PROTECT, to='nomencladores.municipio'),
        ),
    ]
