# Generated by Django 4.0.1 on 2022-05-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salvas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salvas',
            options={'verbose_name': 'Salva y Restaura', 'verbose_name_plural': 'Salvas y Restauras'},
        ),
    ]
