
def init_data(apps, schema_editor):
    provincia = apps.get_model('nomencladores', "Provincia")
    municipio = apps.get_model('nomencladores', "Municipio")

    data_prov = [
        provincia(codigo = 1, nombre = 'Pinar del Río'),
        provincia(codigo = 2, nombre = 'Artemisa'),
        provincia(codigo = 3, nombre = 'La Habana'),
        provincia(codigo = 4, nombre = 'Mayabeque'),
        provincia(codigo = 5, nombre = 'Matanzas'),
        provincia(codigo = 6, nombre = 'Cienfuegos'),
        provincia(codigo = 7, nombre = 'Villa Clara'),
        provincia(codigo = 8, nombre = 'Sancti Spíritus'),
        provincia(codigo = 9, nombre = 'Ciego de Ávila'),
        provincia(codigo = 10, nombre = 'Camagüey'),
        provincia(codigo = 11, nombre = 'Las Tunas'),
        provincia(codigo = 12, nombre = 'Granma'),
        provincia(codigo = 13, nombre = 'Holguín'),
        provincia(codigo = 14, nombre = 'Santiago de Cuba'),
        provincia(codigo = 15, nombre = 'Guantánamo'),
        provincia(codigo = 16, nombre = 'Isla de la Juventud')
    ]
    db_alias = schema_editor.connection.alias
    provincia.objects.using(db_alias).bulk_create(data_prov)

    data_mun = [
        municipio(codigo = 101, provincia = provincia.objects.get(codigo=1), nombre = 'Consolación del Sur'),
        municipio(codigo = 102, provincia = provincia.objects.get(codigo=1), nombre = 'Guanes'),
        municipio(codigo = 103, provincia = provincia.objects.get(codigo=1), nombre = 'La Palma'),
        municipio(codigo = 104, provincia = provincia.objects.get(codigo=1), nombre = 'Los Palacios'),
        municipio(codigo = 105, provincia = provincia.objects.get(codigo=1), nombre = 'Mantua'),
        municipio(codigo = 106, provincia = provincia.objects.get(codigo=1), nombre = 'Minas de Matahambre'),
        municipio(codigo = 107, provincia = provincia.objects.get(codigo=1), nombre = 'Pinar del Río'),
        municipio(codigo = 108, provincia = provincia.objects.get(codigo=1), nombre = 'San Juan y Martínez'),
        municipio(codigo = 109, provincia = provincia.objects.get(codigo=1), nombre = 'San Luis'),
        municipio(codigo = 110, provincia = provincia.objects.get(codigo=1), nombre = 'Sandino'),
        municipio(codigo = 111, provincia = provincia.objects.get(codigo=1), nombre = 'Viñales'),
        municipio(codigo = 201, provincia = provincia.objects.get(codigo=2), nombre = 'Mariel'),
        municipio(codigo = 202, provincia = provincia.objects.get(codigo=2), nombre = 'Guanajay'),
        municipio(codigo = 203, provincia = provincia.objects.get(codigo=2), nombre = 'Caimito'),
        municipio(codigo = 204, provincia = provincia.objects.get(codigo=2), nombre = 'Bauta'),
        municipio(codigo = 205, provincia = provincia.objects.get(codigo=2), nombre = 'San Antonio de los Baños'),
        municipio(codigo = 206, provincia = provincia.objects.get(codigo=2), nombre = 'Güira de Melena'),
        municipio(codigo = 207, provincia = provincia.objects.get(codigo=2), nombre = 'Alquízar'),
        municipio(codigo = 208, provincia = provincia.objects.get(codigo=2), nombre = 'Artemisa'),
        municipio(codigo = 209, provincia = provincia.objects.get(codigo=2), nombre = 'Bahía Honda'),
        municipio(codigo = 210, provincia = provincia.objects.get(codigo=2), nombre = 'Candelaria'),
        municipio(codigo = 211, provincia = provincia.objects.get(codigo=2), nombre = 'San Cristóbal'),
        municipio(codigo = 301, provincia = provincia.objects.get(codigo=3), nombre = 'Arroyo Naranjo'),
        municipio(codigo = 302, provincia = provincia.objects.get(codigo=3), nombre = 'Boyeros'),
        municipio(codigo = 303, provincia = provincia.objects.get(codigo=3), nombre = 'Centro Habana'),
        municipio(codigo = 304, provincia = provincia.objects.get(codigo=3), nombre = 'Cerro'),
        municipio(codigo = 305, provincia = provincia.objects.get(codigo=3), nombre = 'Cotorro'),
        municipio(codigo = 306, provincia = provincia.objects.get(codigo=3), nombre = 'Diez de Octubre'),
        municipio(codigo = 307, provincia = provincia.objects.get(codigo=3), nombre = 'Guanabacoa'),
        municipio(codigo = 308, provincia = provincia.objects.get(codigo=3), nombre = 'La Habana del Este'),
        municipio(codigo = 309, provincia = provincia.objects.get(codigo=3), nombre = 'La Habana Vieja'),
        municipio(codigo = 310, provincia = provincia.objects.get(codigo=3), nombre = 'La Lisa'),
        municipio(codigo = 311, provincia = provincia.objects.get(codigo=3), nombre = 'Marianao'),
        municipio(codigo = 312, provincia = provincia.objects.get(codigo=3), nombre = 'Playa'),
        municipio(codigo = 313, provincia = provincia.objects.get(codigo=3), nombre = 'Plaza de la Revolución'),
        municipio(codigo = 314, provincia = provincia.objects.get(codigo=3), nombre = 'Regla'),
        municipio(codigo = 315, provincia = provincia.objects.get(codigo=3), nombre = 'San Miguel del Padrón'),
        municipio(codigo = 401, provincia = provincia.objects.get(codigo=4), nombre = 'Bejucal'),
        municipio(codigo = 402, provincia = provincia.objects.get(codigo=4), nombre = 'San José de las Lajas'),
        municipio(codigo = 403, provincia = provincia.objects.get(codigo=4), nombre = 'Jaruco'),
        municipio(codigo = 404, provincia = provincia.objects.get(codigo=4), nombre = 'Santa Cruz del Norte'),
        municipio(codigo = 405, provincia = provincia.objects.get(codigo=4), nombre = 'Madruga'),
        municipio(codigo = 406, provincia = provincia.objects.get(codigo=4), nombre = 'Nueva Paz'),
        municipio(codigo = 407, provincia = provincia.objects.get(codigo=4), nombre = 'San Nicolás de Bari'),
        municipio(codigo = 408, provincia = provincia.objects.get(codigo=4), nombre = 'Güines'),
        municipio(codigo = 409, provincia = provincia.objects.get(codigo=4), nombre = 'Melena del Sur'),
        municipio(codigo = 410, provincia = provincia.objects.get(codigo=4), nombre = 'Batabanó'),
        municipio(codigo = 411, provincia = provincia.objects.get(codigo=4), nombre = 'Quivicán'),
        municipio(codigo = 501, provincia = provincia.objects.get(codigo=5), nombre = 'Calimete'),
        municipio(codigo = 502, provincia = provincia.objects.get(codigo=5), nombre = 'Cárdenas'),
        municipio(codigo = 503, provincia = provincia.objects.get(codigo=5), nombre = 'Ciénaga de Zapata'),
        municipio(codigo = 504, provincia = provincia.objects.get(codigo=5), nombre = 'Colón'),
        municipio(codigo = 505, provincia = provincia.objects.get(codigo=5), nombre = 'Jagüey Grande'),
        municipio(codigo = 506, provincia = provincia.objects.get(codigo=5), nombre = 'Jovellanos'),
        municipio(codigo = 507, provincia = provincia.objects.get(codigo=5), nombre = 'Limonar'),
        municipio(codigo = 508, provincia = provincia.objects.get(codigo=5), nombre = 'Los Arabos'),
        municipio(codigo = 509, provincia = provincia.objects.get(codigo=5), nombre = 'Martí'),
        municipio(codigo = 510, provincia = provincia.objects.get(codigo=5), nombre = 'Matanzas'),
        municipio(codigo = 511, provincia = provincia.objects.get(codigo=5), nombre = 'Pedro Betancourt'),
        municipio(codigo = 512, provincia = provincia.objects.get(codigo=5), nombre = 'Perico'),
        municipio(codigo = 513, provincia = provincia.objects.get(codigo=5), nombre = 'Unión de Reyes'),
        municipio(codigo = 601, provincia = provincia.objects.get(codigo=6), nombre = 'Abreus'),
        municipio(codigo = 602, provincia = provincia.objects.get(codigo=6), nombre = 'Aguada de Pasajeros'),
        municipio(codigo = 603, provincia = provincia.objects.get(codigo=6), nombre = 'Cienfuegos'),
        municipio(codigo = 604, provincia = provincia.objects.get(codigo=6), nombre = 'Cruces'),
        municipio(codigo = 605, provincia = provincia.objects.get(codigo=6), nombre = 'Cumanayagua'),
        municipio(codigo = 606, provincia = provincia.objects.get(codigo=6), nombre = 'Lajas'),
        municipio(codigo = 607, provincia = provincia.objects.get(codigo=6), nombre = 'Palmira'),
        municipio(codigo = 608, provincia = provincia.objects.get(codigo=6), nombre = 'Rondas'),
        municipio(codigo = 609, provincia = provincia.objects.get(codigo=6), nombre = 'Congolas'),
        municipio(codigo = 701, provincia = provincia.objects.get(codigo=7), nombre = 'Caibarién'),
        municipio(codigo = 702, provincia = provincia.objects.get(codigo=7), nombre = 'Camajuaní'),
        municipio(codigo = 703, provincia = provincia.objects.get(codigo=7), nombre = 'Cifuentes'),
        municipio(codigo = 704, provincia = provincia.objects.get(codigo=7), nombre = 'Corralillo'),
        municipio(codigo = 705, provincia = provincia.objects.get(codigo=7), nombre = 'Encrucijada'),
        municipio(codigo = 706, provincia = provincia.objects.get(codigo=7), nombre = 'Manicaragua'),
        municipio(codigo = 707, provincia = provincia.objects.get(codigo=7), nombre = 'Placetas'),
        municipio(codigo = 708, provincia = provincia.objects.get(codigo=7), nombre = 'Quemado de Güines'),
        municipio(codigo = 709, provincia = provincia.objects.get(codigo=7), nombre = 'Ranchuelo'),
        municipio(codigo = 710, provincia = provincia.objects.get(codigo=7), nombre = 'Remedios'),
        municipio(codigo = 711, provincia = provincia.objects.get(codigo=7), nombre = 'Sagua la Grande'),
        municipio(codigo = 712, provincia = provincia.objects.get(codigo=7), nombre = 'Santa Clara'),
        municipio(codigo = 713, provincia = provincia.objects.get(codigo=7), nombre = 'Santo Domingo'),
        municipio(codigo = 801, provincia = provincia.objects.get(codigo=8), nombre = 'Sancti Spíritus'),
        municipio(codigo = 802, provincia = provincia.objects.get(codigo=8), nombre = 'Trinidad'),
        municipio(codigo = 803, provincia = provincia.objects.get(codigo=8), nombre = 'Cabaiguán'),
        municipio(codigo = 804, provincia = provincia.objects.get(codigo=8), nombre = 'Yaguajay'),
        municipio(codigo = 805, provincia = provincia.objects.get(codigo=8), nombre = 'Jatibonico'),
        municipio(codigo = 806, provincia = provincia.objects.get(codigo=8), nombre = 'Taguasco'),
        municipio(codigo = 807, provincia = provincia.objects.get(codigo=8), nombre = 'Fomento'),
        municipio(codigo = 808, provincia = provincia.objects.get(codigo=8), nombre = 'La Sierpe'),
        municipio(codigo = 901, provincia = provincia.objects.get(codigo=9), nombre = 'Ciego de Ávila'),
        municipio(codigo = 902, provincia = provincia.objects.get(codigo=9), nombre = 'Morón'),
        municipio(codigo = 903, provincia = provincia.objects.get(codigo=9), nombre = 'Chambas'),
        municipio(codigo = 904, provincia = provincia.objects.get(codigo=9), nombre = 'Ciro Redondo'),
        municipio(codigo = 905, provincia = provincia.objects.get(codigo=9), nombre = 'Majagua'),
        municipio(codigo = 906, provincia = provincia.objects.get(codigo=9), nombre = 'Florencia'),
        municipio(codigo = 907, provincia = provincia.objects.get(codigo=9), nombre = 'Venezuela'),
        municipio(codigo = 908, provincia = provincia.objects.get(codigo=9), nombre = 'Baraguá'),
        municipio(codigo = 909, provincia = provincia.objects.get(codigo=9), nombre = 'Primero de Enero'),
        municipio(codigo = 910, provincia = provincia.objects.get(codigo=9), nombre = 'Bolivia'),
        municipio(codigo = 1001, provincia = provincia.objects.get(codigo=10), nombre = 'Camagüey'),
        municipio(codigo = 1002, provincia = provincia.objects.get(codigo=10), nombre = 'Guáimaro'),
        municipio(codigo = 1003, provincia = provincia.objects.get(codigo=10), nombre = 'Nuevitas'),
        municipio(codigo = 1004, provincia = provincia.objects.get(codigo=10), nombre = 'Céspedes'),
        municipio(codigo = 1005, provincia = provincia.objects.get(codigo=10), nombre = 'Jimaguayú'),
        municipio(codigo = 1006, provincia = provincia.objects.get(codigo=10), nombre = 'Sibanicú'),
        municipio(codigo = 1007, provincia = provincia.objects.get(codigo=10), nombre = 'Esmeralda'),
        municipio(codigo = 1008, provincia = provincia.objects.get(codigo=10), nombre = 'Minas'),
        municipio(codigo = 1009, provincia = provincia.objects.get(codigo=10), nombre = 'Sierra de Cubitas'),
        municipio(codigo = 1010, provincia = provincia.objects.get(codigo=10), nombre = 'Florida'),
        municipio(codigo = 1011, provincia = provincia.objects.get(codigo=10), nombre = 'Najasa'),
        municipio(codigo = 1012, provincia = provincia.objects.get(codigo=10), nombre = 'Vertientes'),        
        municipio(codigo = 1013, provincia = provincia.objects.get(codigo=10), nombre = 'Santa Cruz del Sur'),
        municipio(codigo = 1101, provincia = provincia.objects.get(codigo=11), nombre = 'Manatí'),
        municipio(codigo = 1102, provincia = provincia.objects.get(codigo=11), nombre = 'Puerto Padre'),
        municipio(codigo = 1103, provincia = provincia.objects.get(codigo=11), nombre = 'Jesús Menéndez'),
        municipio(codigo = 1104, provincia = provincia.objects.get(codigo=11), nombre = 'Majibacoa'),
        municipio(codigo = 1105, provincia = provincia.objects.get(codigo=11), nombre = 'Las Tunas'),
        municipio(codigo = 1106, provincia = provincia.objects.get(codigo=11), nombre = 'Jobabo'),
        municipio(codigo = 1107, provincia = provincia.objects.get(codigo=11), nombre = 'Colombia'),        
        municipio(codigo = 1108, provincia = provincia.objects.get(codigo=11), nombre = 'Amancio'),
        municipio(codigo = 1201, provincia = provincia.objects.get(codigo=12), nombre = 'Bartolomé Masó'),
        municipio(codigo = 1202, provincia = provincia.objects.get(codigo=12), nombre = 'Bayamo'),
        municipio(codigo = 1203, provincia = provincia.objects.get(codigo=12), nombre = 'Buey Arriba'),
        municipio(codigo = 1204, provincia = provincia.objects.get(codigo=12), nombre = 'Campechuela'),
        municipio(codigo = 1205, provincia = provincia.objects.get(codigo=12), nombre = 'Cauto Cristo'),
        municipio(codigo = 1206, provincia = provincia.objects.get(codigo=12), nombre = 'Guisa'),
        municipio(codigo = 1207, provincia = provincia.objects.get(codigo=12), nombre = 'Jiguaní'),
        municipio(codigo = 1208, provincia = provincia.objects.get(codigo=12), nombre = 'Manzanillo'),
        municipio(codigo = 1209, provincia = provincia.objects.get(codigo=12), nombre = 'Media Luna'),
        municipio(codigo = 1210, provincia = provincia.objects.get(codigo=12), nombre = 'Niquero'),
        municipio(codigo = 1211, provincia = provincia.objects.get(codigo=12), nombre = 'Pilón'),
        municipio(codigo = 1212, provincia = provincia.objects.get(codigo=12), nombre = 'Río Cauto'),
        municipio(codigo = 1212, provincia = provincia.objects.get(codigo=12), nombre = 'Yara'),
        municipio(codigo = 1301, provincia = provincia.objects.get(codigo=13), nombre = 'Antilla'),
        municipio(codigo = 1302, provincia = provincia.objects.get(codigo=13), nombre = 'Báguanos'),
        municipio(codigo = 1303, provincia = provincia.objects.get(codigo=13), nombre = 'Banes'),
        municipio(codigo = 1304, provincia = provincia.objects.get(codigo=13), nombre = 'Cacocum'),
        municipio(codigo = 1305, provincia = provincia.objects.get(codigo=13), nombre = 'Calixto García'),
        municipio(codigo = 1306, provincia = provincia.objects.get(codigo=13), nombre = 'Cueto'),
        municipio(codigo = 1307, provincia = provincia.objects.get(codigo=13), nombre = 'Frank País'),
        municipio(codigo = 1308, provincia = provincia.objects.get(codigo=13), nombre = 'Gibara'),
        municipio(codigo = 1309, provincia = provincia.objects.get(codigo=13), nombre = 'Holguín'),
        municipio(codigo = 1310, provincia = provincia.objects.get(codigo=13), nombre = 'Mayarí'),
        municipio(codigo = 1311, provincia = provincia.objects.get(codigo=13), nombre = 'Moa'),
        municipio(codigo = 1312, provincia = provincia.objects.get(codigo=13), nombre = 'Rafael Freyre'),
        municipio(codigo = 1313, provincia = provincia.objects.get(codigo=13), nombre = 'Sagua de Tánamo'),
        municipio(codigo = 1314, provincia = provincia.objects.get(codigo=13), nombre = 'Urbano Noris'),
        municipio(codigo = 1401, provincia = provincia.objects.get(codigo=14), nombre = 'Contramaestre'),
        municipio(codigo = 1402, provincia = provincia.objects.get(codigo=14), nombre = 'Guamá'),
        municipio(codigo = 1403, provincia = provincia.objects.get(codigo=14), nombre = 'Mella'),
        municipio(codigo = 1404, provincia = provincia.objects.get(codigo=14), nombre = 'Palma Soriano'),
        municipio(codigo = 1405, provincia = provincia.objects.get(codigo=14), nombre = 'San Luis'),
        municipio(codigo = 1406, provincia = provincia.objects.get(codigo=14), nombre = 'Santiago de Cuba'),
        municipio(codigo = 1407, provincia = provincia.objects.get(codigo=14), nombre = 'Segundo Frente'),
        municipio(codigo = 1408, provincia = provincia.objects.get(codigo=14), nombre = 'Songo-La Maya'),
        municipio(codigo = 1409, provincia = provincia.objects.get(codigo=14), nombre = 'Tercer Frente'),
        municipio(codigo = 1501, provincia = provincia.objects.get(codigo=15), nombre = 'Baracoa'),
        municipio(codigo = 1502, provincia = provincia.objects.get(codigo=15), nombre = 'Caimanera'),
        municipio(codigo = 1503, provincia = provincia.objects.get(codigo=15), nombre = 'El Salvador'),
        municipio(codigo = 1504, provincia = provincia.objects.get(codigo=15), nombre = 'Guantánamo'),
        municipio(codigo = 1505, provincia = provincia.objects.get(codigo=15), nombre = 'Imías'),
        municipio(codigo = 1506, provincia = provincia.objects.get(codigo=15), nombre = 'Maisí'),
        municipio(codigo = 1507, provincia = provincia.objects.get(codigo=15), nombre = 'Manuel Tames'),
        municipio(codigo = 1508, provincia = provincia.objects.get(codigo=15), nombre = 'Niceto Pérez'),
        municipio(codigo = 1509, provincia = provincia.objects.get(codigo=15), nombre = 'San Antonio del Sur'),        
        municipio(codigo = 1510, provincia = provincia.objects.get(codigo=15), nombre = 'Yateras'),
        municipio(codigo = 1601, provincia = provincia.objects.get(codigo=16), nombre = 'Isla de la Juventud')                      
    ]
    db_alias = schema_editor.connection.alias
    municipio.objects.using(db_alias).bulk_create(data_mun)