# Generated by Django 4.0.1 on 2022-05-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trazas', '0003_alter_logentry_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='ip',
        ),
    ]
