# Generated by Django 3.2.9 on 2021-11-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('idalmacen', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipoalmacen', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoCliente',
            fields=[
                ('numcontratocliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('vigencia', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contrato_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoProveedor',
            fields=[
                ('numcontratoproveedor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('vigencia', models.DateField()),
            ],
            options={
                'db_table': 'contrato_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaCliente',
            fields=[
                ('codfacturacliente', models.AutoField(primary_key=True, serialize=False)),
                ('numcontratocliente', models.BigIntegerField()),
                ('idproducto', models.IntegerField()),
                ('precio', models.FloatField()),
                ('fechafact', models.DateField()),
            ],
            options={
                'db_table': 'factura_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('codfacturaprov', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('fechafacturaprov', models.DateField()),
            ],
            options={
                'db_table': 'factura_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idhistorial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('numcontratoproveedor', models.BigIntegerField()),
                ('idproducto', models.IntegerField()),
            ],
            options={
                'db_table': 'historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroControlSolicitud',
            fields=[
                ('numsolicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('numcontratocliente', models.IntegerField()),
                ('numcontratoproveedor', models.IntegerField()),
                ('fechasol', models.DateField()),
            ],
            options={
                'db_table': 'registro_control_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('numsolicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fechasol', models.DateField()),
                ('numcontratoproveedor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_title', models.CharField(max_length=100)),
                ('user_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('numcontratocliente', models.OneToOneField(db_column='numcontratocliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ImportApp.contratocliente')),
                ('nomcliente', models.CharField(max_length=45)),
                ('osde', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('numcontratoproveedor', models.OneToOneField(db_column='numcontratoproveedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ImportApp.contratoproveedor')),
                ('nomproveedor', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
    ]
