# Generated by Django 3.2.9 on 2021-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImportApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='CodigoProducto',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='DescripcionProducto',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
