# Generated by Django 3.2.9 on 2021-11-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImportApp', '0002_auto_20211104_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoPais', models.CharField(max_length=5, verbose_name='Código')),
                ('Pais', models.CharField(max_length=50, verbose_name='País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='Pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ImportApp.pais', verbose_name='País'),
            preserve_default=False,
        ),
    ]
