# Generated by Django 3.2.9 on 2021-11-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImportApp', '0003_auto_20211104_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Cantidad',
            field=models.FloatField(verbose_name='Cantidad'),
        ),
    ]
