# Generated by Django 4.0.1 on 2022-05-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte_solicitud',
            options={'verbose_name': ('Reporte de Solicitud',), 'verbose_name_plural': 'Reportes de Solicitudes'},
        ),
    ]
