# Generated by Django 4.0.1 on 2022-05-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0002_alter_reporte_solicitud_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': ('Reporte de Proveedor',),
                'verbose_name_plural': 'Reportes de Proveedores',
            },
        ),
    ]
