# Generated by Django 4.0.1 on 2022-04-28 13:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0002_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialistaCOMEX',
            fields=[
                ('idespecialista', models.OneToOneField(db_column='idespecialista', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('categoria', models.CharField(choices=[('PZ', 'PPA'), ('Equipo', 'Equipo'), ('Batería', 'Batería'), ('Neumático', 'Neumático')], default='PZ', max_length=10)),
            ],
            options={
                'verbose_name': 'Especialista COMEX',
                'verbose_name_plural': 'Especialistas COMEX',
                'db_table': 'especialista_comex',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oferta_Equipo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 4, 28), verbose_name='Fecha de la Oferta')),
                ('validez', models.DateField()),
                ('tipo', models.CharField(choices=[('Oferta', 'Oferta'), ('Reoferta', 'Reoferta'), ('Contraoferta', 'Contraoferta')], default='Oferta', max_length=30)),
            ],
            options={
                'verbose_name': 'Oferta de Equipo',
                'verbose_name_plural': 'Ofertas de Equipos',
                'db_table': 'oferta_equipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oferta_Equipo_Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=4)),
                ('precio', models.FloatField(max_length=4)),
                ('importe', models.FloatField(max_length=4)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'oferta_equipo_proxy',
                'managed': True,
            },
        ),
    ]
