# Generated by Django 4.0.1 on 2022-06-15 23:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta_Bateria',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 6, 15), verbose_name='Fecha de la Oferta')),
                ('validez', models.CharField(choices=[('30 Días', '30 Días'), ('60 Días', '60 Días')], default='30 Días', max_length=30)),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=30)),
                ('valor_estimado', models.FloatField(verbose_name='Valor Estimado')),
                ('monto_total', models.FloatField(null=True, verbose_name='Monto Total')),
            ],
            options={
                'verbose_name': 'Oferta de Baterías',
                'verbose_name_plural': 'Oferta de Baterías',
                'db_table': 'oferta_baterias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oferta_Equipo',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 6, 15), verbose_name='Fecha de la Oferta')),
                ('validez', models.CharField(choices=[('30 Días', '30 Días'), ('60 Días', '60 Días')], default='30 Días', max_length=30)),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=30)),
                ('valor_estimado', models.FloatField(verbose_name='Valor Estimado')),
                ('monto_total', models.FloatField(null=True, verbose_name='Monto Total')),
            ],
            options={
                'verbose_name': 'Oferta de Equipo',
                'verbose_name_plural': 'Ofertas de Equipos',
                'db_table': 'oferta_equipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oferta_Neumatico',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 6, 15), verbose_name='Fecha de la Oferta')),
                ('validez', models.CharField(choices=[('30 Días', '30 Días'), ('60 Días', '60 Días')], default='30 Días', max_length=30)),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=30)),
                ('valor_estimado', models.FloatField(verbose_name='Valor Estimado')),
                ('monto_total', models.FloatField(null=True, verbose_name='Monto Total')),
                ('especialista', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta de Neumáticos',
                'verbose_name_plural': 'Oferta de Neumáticos',
                'db_table': 'oferta_neumaticos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oferta_PPA',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 6, 15), verbose_name='Fecha de la Oferta')),
                ('validez', models.CharField(choices=[('30 Días', '30 Días'), ('60 Días', '60 Días')], default='30 Días', max_length=30)),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=30)),
                ('valor_estimado', models.FloatField(verbose_name='Valor Estimado')),
                ('monto_total', models.FloatField(null=True, verbose_name='Monto Total')),
                ('especialista', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta de Partes y Piezas',
                'verbose_name_plural': 'Ofertas de Partes y Piezas',
                'db_table': 'oferta_ppa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oferta_PPA_Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('importe', models.FloatField()),
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_ppa_proxy')),
                ('solicitud', models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.oferta_ppa')),
            ],
            options={
                'verbose_name': 'Partes y Piezas',
                'verbose_name_plural': 'Partes y Piezas',
                'db_table': 'oferta_ppa_proxy',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='oferta_ppa',
            name='idproducto',
            field=models.ManyToManyField(through='COMEX.Oferta_PPA_Proxy', to='Solicitudes.Solicitud_PPA_Proxy', verbose_name='Equipos'),
        ),
        migrations.AddField(
            model_name='oferta_ppa',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.pais', verbose_name='País de Origen de la carga'),
        ),
        migrations.AddField(
            model_name='oferta_ppa',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='codmincex', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='oferta_ppa',
            name='solicitud',
            field=models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_ppa', verbose_name='Solicitud'),
        ),
        migrations.CreateModel(
            name='Oferta_Neumatico_Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField(blank=True, null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('neumatico', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_neumatico_proxy')),
                ('solicitud', models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.oferta_neumatico')),
            ],
            options={
                'verbose_name': 'Neumático',
                'verbose_name_plural': 'Neumáticos',
                'db_table': 'oferta_neumatico_proxy',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='oferta_neumatico',
            name='neumaticos',
            field=models.ManyToManyField(through='COMEX.Oferta_Neumatico_Proxy', to='Solicitudes.Solicitud_Neumatico_Proxy', verbose_name='Neumáticos'),
        ),
        migrations.AddField(
            model_name='oferta_neumatico',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.pais', verbose_name='País de Origen de la carga'),
        ),
        migrations.AddField(
            model_name='oferta_neumatico',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='codmincex', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='oferta_neumatico',
            name='solicitud',
            field=models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_neumatico', verbose_name='Solicitud'),
        ),
        migrations.CreateModel(
            name='Oferta_Equipo_Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField(blank=True, null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('equipo', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_equipo_proxy')),
                ('solicitud', models.ForeignKey(db_column='numsolicitud', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.oferta_equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'oferta_equipo_proxy',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='equipos',
            field=models.ManyToManyField(through='COMEX.Oferta_Equipo_Proxy', to='Solicitudes.Solicitud_Equipo_Proxy', verbose_name='Equipos'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='especialista',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.pais', verbose_name='País de Origen de la carga'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='codmincex', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='solicitud',
            field=models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_equipo', verbose_name='Solicitud'),
        ),
        migrations.CreateModel(
            name='Oferta_Bateria_Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField(blank=True, null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('bateria', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_bateria_proxy')),
                ('solicitud', models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.oferta_bateria')),
            ],
            options={
                'verbose_name': 'Batería',
                'verbose_name_plural': 'Baterías',
                'db_table': 'oferta_bateria_proxy',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='oferta_bateria',
            name='baterias',
            field=models.ManyToManyField(through='COMEX.Oferta_Bateria_Proxy', to='Solicitudes.Solicitud_Bateria_Proxy', verbose_name='Baterías'),
        ),
        migrations.AddField(
            model_name='oferta_bateria',
            name='especialista',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oferta_bateria',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.pais', verbose_name='País de Origen de la carga'),
        ),
        migrations.AddField(
            model_name='oferta_bateria',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='codmincex', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='oferta_bateria',
            name='solicitud',
            field=models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_bateria', verbose_name='Solicitud'),
        ),
    ]
