# Generated by Django 4.0.1 on 2022-04-01 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_group_options_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialistaCOMEX',
            fields=[
                ('idespecialista', models.OneToOneField(db_column='idespecialista', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('categoria', models.CharField(choices=[('PZ', 'PPA'), ('EQ', 'Equipo')], default='PZ', max_length=10)),
            ],
            options={
                'verbose_name': 'Especialista COMEX',
                'verbose_name_plural': 'Especialistas COMEX',
                'db_table': 'especialista_comex',
                'managed': True,
            },
        ),
    ]
