# Generated by Django 4.0.1 on 2022-04-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Solicitudes', '0001_initial'),
        ('COMEX', '0001_initial'),
        ('Nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_equipo_proxy',
            name='equipo',
            field=models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_equipo_proxy'),
        ),
        migrations.AddField(
            model_name='oferta_equipo_proxy',
            name='solicitud',
            field=models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.oferta_equipo'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='equipos',
            field=models.ManyToManyField(through='COMEX.Oferta_Equipo_Proxy', to='Solicitudes.Solicitud_Equipo_Proxy', verbose_name='Equipos'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='especialista',
            field=models.ForeignKey(db_column='idespecialista', on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='idpais', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.pais', verbose_name='País de Origen de la carga'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='codmincex', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='solicitud',
            field=models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_equipo', verbose_name='Solicitud'),
        ),
    ]
