# Generated by Django 4.0.1 on 2022-04-25 15:37

import COMEX.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('COMEX', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistacomex',
            name='categoria',
            field=models.CharField(choices=[('PZ', 'PPA'), ('Equipo', 'Equipo'), ('Batería', 'Batería'), ('Neumático', 'Neumático')], default='PZ', max_length=10),
        ),
        migrations.AlterField(
            model_name='especialistacomex',
            name='idespecialista',
            field=models.OneToOneField(db_column='idespecialista', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
