# Generated by Django 4.0.1 on 2022-04-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudOferta',
            fields=[
                ('idnumoferta', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
