# Generated by Django 4.0.1 on 2022-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta_equipo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='estado',
            field=models.CharField(choices=[('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=30),
        ),
    ]
