# Generated by Django 4.0.1 on 2022-04-27 08:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0009_remove_solicitud_bateria_idespecialista_and_more'),
        ('Nomencladores', '0025_alter_marca_codigomarca'),
        ('COMEX', '0002_alter_especialistacomex_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta_Equipo',
            fields=[
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 4, 27), verbose_name='Fecha de la Oferta')),
                ('validez', models.DateField()),
                ('tipo', models.CharField(choices=[('Oferta', 'Oferta'), ('Reoferta', 'Reoferta'), ('Contraoferta', 'Contraoferta')], default='Oferta', max_length=30)),
                ('solicitud', models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Solicitudes.solicitud_equipo', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Oferta de Equipo',
                'verbose_name_plural': 'Ofertas de Equipos',
                'db_table': 'oferta_equipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oferta_Equipo_Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=4)),
                ('precio', models.FloatField(max_length=4)),
                ('importe', models.FloatField(max_length=4)),
                ('equipo', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_equipo_proxy')),
                ('solicitud', models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.oferta_equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'oferta_equipo_proxy',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='equipos',
            field=models.ManyToManyField(through='COMEX.Oferta_Equipo_Proxy', to='Solicitudes.Solicitud_Equipo_Proxy', verbose_name='Equipos'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='idpais', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.pais', verbose_name='País de Origen de la carga'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='codmincex', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
    ]
