# Generated by Django 4.0.1 on 2022-04-27 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0003_oferta_equipo_oferta_equipo_proxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_equipo',
            name='especialista',
            field=models.ForeignKey(db_column='idespecialista', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex'),
            preserve_default=False,
        ),
    ]
