# Generated by Django 4.0.1 on 2022-04-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0003_remove_oferta_equipo_tipo_oferta_equipo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_equipo',
            name='validez',
            field=models.CharField(choices=[('30 Días', '30 Días'), ('60 Días', '60 Días')], default='30 Días', max_length=30),
        ),
    ]
