# Generated by Django 4.0.1 on 2022-04-28 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0004_oferta_equipo_especialista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_equipo',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 28), verbose_name='Fecha de la Oferta'),
        ),
    ]
