# Generated by Django 4.0.1 on 2022-04-29 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0004_alter_oferta_equipo_validez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_equipo',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 29), verbose_name='Fecha de la Oferta'),
        ),
        migrations.AlterField(
            model_name='oferta_equipo',
            name='numero',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número'),
        ),
    ]
