# Generated by Django 4.0.1 on 2022-04-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0005_alter_oferta_equipo_fecha_alter_oferta_equipo_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_equipo_proxy',
            name='cantidad',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='oferta_equipo_proxy',
            name='importe',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='oferta_equipo_proxy',
            name='precio',
            field=models.FloatField(max_length=8),
        ),
    ]
