# Generated by Django 4.0.1 on 2022-06-27 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0005_alter_oferta_bateria_fecha_alter_oferta_equipo_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_bateria',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de la Oferta'),
        ),
        migrations.AlterField(
            model_name='oferta_equipo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de la Oferta'),
        ),
        migrations.AlterField(
            model_name='oferta_neumatico',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de la Oferta'),
        ),
        migrations.AlterField(
            model_name='oferta_ppa',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de la Oferta'),
        ),
    ]
