# Generated by Django 4.0.1 on 2022-05-01 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0006_alter_oferta_equipo_proxy_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_equipo',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 1), verbose_name='Fecha de la Oferta'),
        ),
    ]
