# Generated by Django 4.0.1 on 2022-07-02 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0006_alter_oferta_bateria_fecha_alter_oferta_equipo_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta_equipo_proxy',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='oferta_equipo_proxy',
            name='oferta',
            field=models.ForeignKey(db_column='numero', db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.oferta_equipo'),
            preserve_default=False,
        ),
    ]
