# Generated by Django 4.0.1 on 2022-05-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0006_alter_cliente_numcontratocliente'),
        ('COMEX', '0007_alter_oferta_equipo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_equipo',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.pais', verbose_name='País de Origen de la carga'),
        ),
    ]
