# Generated by Django 4.0.1 on 2022-05-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0006_alter_cliente_numcontratocliente'),
        ('COMEX', '0008_alter_oferta_equipo_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_equipo',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='codmincex', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
    ]
