# Generated by Django 4.0.1 on 2022-05-02 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0010_alter_oferta_equipo_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_equipo',
            name='valor_estimado',
            field=models.FloatField(default=1, max_length=10, verbose_name='Valor Estimado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferta_equipo',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 2), verbose_name='Fecha de la Oferta'),
        ),
    ]
