# Generated by Django 4.0.1 on 2022-05-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0013_alter_oferta_equipo_proxy_importe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_equipo_proxy',
            name='importe',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='oferta_equipo_proxy',
            name='precio',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
    ]
