# Generated by Django 4.0.1 on 2022-05-06 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0014_alter_oferta_equipo_proxy_importe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta_ppa',
            old_name='equipos',
            new_name='idproducto',
        ),
        migrations.RenameField(
            model_name='oferta_ppa_proxy',
            old_name='equipo',
            new_name='idproducto',
        ),
        migrations.AlterField(
            model_name='oferta_equipo',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 6), verbose_name='Fecha de la Oferta'),
        ),
        migrations.AlterField(
            model_name='oferta_ppa',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 6), verbose_name='Fecha de la Oferta'),
        ),
    ]
