# Generated by Django 4.0.1 on 2022-05-06 05:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0007_alter_solicitud_bateria_fechasol_and_more'),
        ('Nomencladores', '0007_alter_marca_codigomarca'),
        ('COMEX', '0015_rename_equipos_oferta_ppa_idproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta_Bateria',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 5, 6), verbose_name='Fecha de la Oferta')),
                ('validez', models.CharField(choices=[('30 Días', '30 Días'), ('60 Días', '60 Días')], default='30 Días', max_length=30)),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=30)),
                ('valor_estimado', models.FloatField(max_length=10, verbose_name='Valor Estimado')),
            ],
            options={
                'verbose_name': 'Oferta de Baterías',
                'verbose_name_plural': 'Oferta de Baterías',
                'db_table': 'oferta_baterias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oferta_Neumatico',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 5, 6), verbose_name='Fecha de la Oferta')),
                ('validez', models.CharField(choices=[('30 Días', '30 Días'), ('60 Días', '60 Días')], default='30 Días', max_length=30)),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=30)),
                ('valor_estimado', models.FloatField(max_length=10, verbose_name='Valor Estimado')),
                ('especialista', models.ForeignKey(db_column='idespecialista', on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex')),
            ],
            options={
                'verbose_name': 'Oferta de Neumáticos',
                'verbose_name_plural': 'Oferta de Neumáticos',
                'db_table': 'oferta_neumaticos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oferta_Neumatico_Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=8)),
                ('precio', models.FloatField(blank=True, max_length=8, null=True)),
                ('importe', models.FloatField(blank=True, max_length=8, null=True)),
                ('neumatico', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_neumatico_proxy')),
                ('solicitud', models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.oferta_neumatico')),
            ],
            options={
                'verbose_name': 'Neumático',
                'verbose_name_plural': 'Neumáticos',
                'db_table': 'oferta_neumatico_proxy',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='oferta_neumatico',
            name='neumaticos',
            field=models.ManyToManyField(through='COMEX.Oferta_Neumatico_Proxy', to='Solicitudes.Solicitud_Neumatico_Proxy', verbose_name='Neumáticos'),
        ),
        migrations.AddField(
            model_name='oferta_neumatico',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.pais', verbose_name='País de Origen de la carga'),
        ),
        migrations.AddField(
            model_name='oferta_neumatico',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='codmincex', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='oferta_neumatico',
            name='solicitud',
            field=models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_neumatico', verbose_name='Solicitud'),
        ),
        migrations.CreateModel(
            name='Oferta_Bateria_Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=8)),
                ('precio', models.FloatField(blank=True, max_length=8, null=True)),
                ('importe', models.FloatField(blank=True, max_length=8, null=True)),
                ('bateria', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_bateria_proxy')),
                ('solicitud', models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.oferta_bateria')),
            ],
            options={
                'verbose_name': 'Batería',
                'verbose_name_plural': 'Baterías',
                'db_table': 'oferta_bateria_proxy',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='oferta_bateria',
            name='baterias',
            field=models.ManyToManyField(through='COMEX.Oferta_Bateria_Proxy', to='Solicitudes.Solicitud_Bateria_Proxy', verbose_name='Baterías'),
        ),
        migrations.AddField(
            model_name='oferta_bateria',
            name='especialista',
            field=models.ForeignKey(db_column='idespecialista', on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex'),
        ),
        migrations.AddField(
            model_name='oferta_bateria',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.pais', verbose_name='País de Origen de la carga'),
        ),
        migrations.AddField(
            model_name='oferta_bateria',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='codmincex', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='oferta_bateria',
            name='solicitud',
            field=models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.solicitud_bateria', verbose_name='Solicitud'),
        ),
    ]
