# Generated by Django 4.0.1 on 2022-05-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0018_alter_oferta_equipo_proxy_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_bateria',
            name='monto_total',
            field=models.FloatField(max_length=10, null=True, verbose_name='Monto Total'),
        ),
        migrations.AddField(
            model_name='oferta_equipo',
            name='monto_total',
            field=models.FloatField(max_length=10, null=True, verbose_name='Monto Total'),
        ),
        migrations.AddField(
            model_name='oferta_neumatico',
            name='monto_total',
            field=models.FloatField(max_length=10, null=True, verbose_name='Monto Total'),
        ),
        migrations.AddField(
            model_name='oferta_ppa',
            name='monto_total',
            field=models.FloatField(max_length=10, null=True, verbose_name='Monto Total'),
        ),
    ]
