# Generated by Django 4.0.1 on 2022-05-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0020_alter_oferta_bateria_fecha_alter_oferta_equipo_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta_bateria',
            name='monto_total',
            field=models.FloatField(null=True, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='oferta_bateria',
            name='valor_estimado',
            field=models.FloatField(verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='oferta_bateria_proxy',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oferta_bateria_proxy',
            name='importe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta_bateria_proxy',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta_equipo',
            name='monto_total',
            field=models.FloatField(null=True, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='oferta_equipo',
            name='valor_estimado',
            field=models.FloatField(verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='oferta_equipo_proxy',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oferta_equipo_proxy',
            name='importe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta_equipo_proxy',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta_neumatico',
            name='monto_total',
            field=models.FloatField(null=True, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='oferta_neumatico',
            name='valor_estimado',
            field=models.FloatField(verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='oferta_neumatico_proxy',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oferta_neumatico_proxy',
            name='importe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta_neumatico_proxy',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta_ppa',
            name='monto_total',
            field=models.FloatField(null=True, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='oferta_ppa',
            name='valor_estimado',
            field=models.FloatField(verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='oferta_ppa_proxy',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oferta_ppa_proxy',
            name='importe',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='oferta_ppa_proxy',
            name='precio',
            field=models.FloatField(),
        ),
    ]
