# Generated by Django 4.0.1 on 2022-03-22 02:35

import Solicitudes.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nomencladores', '0005_alter_especialistacomex_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroControlSolicitud',
            fields=[
                ('numsolicitud', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Número')),
                ('fechasol', models.DateField(default=datetime.date(2022, 3, 21), validators=[Solicitudes.models.validate_fecha], verbose_name='Fecha')),
                ('cantidad', models.IntegerField(validators=[Solicitudes.models.validate_cantidad])),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Denegada', 'Denegada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Solicitud',
                'verbose_name_plural': 'Registro de Solicitudes',
                'db_table': 'registro_control_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('numsolicitud', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Número')),
                ('fechasol', models.DateField(default=datetime.date(2022, 3, 21), validators=[Solicitudes.models.validate_fecha], verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10, null=True)),
                ('observaciones', models.TextField(max_length=150, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudesBackupview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Solicitudes_backupview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[Solicitudes.models.validate_cantidad])),
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.producto')),
                ('numsolicitud', models.ForeignKey(db_column='numsolicitud', on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'solicitud_producto',
                'managed': True,
            },
        ),
    ]
