# Generated by Django 4.0.1 on 2022-03-14 01:36

import Solicitudes.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroControlSolicitud',
            fields=[
                ('numsolicitud', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Número')),
                ('fechasol', models.DateField(default=datetime.date(2022, 3, 13), validators=[Solicitudes.models.validate_fecha], verbose_name='Fecha')),
                ('cantidad', models.IntegerField(validators=[Solicitudes.models.validate_cantidad])),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Denegada', 'Denegada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Solicitud',
                'verbose_name_plural': 'Registro de Solicitudes',
                'db_table': 'registro_control_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('numsolicitud', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Número')),
                ('fechasol', models.DateField(default=datetime.date(2022, 3, 13), validators=[Solicitudes.models.validate_fecha], verbose_name='Fecha')),
                ('cantidad', models.IntegerField(validators=[Solicitudes.models.validate_cantidad])),
                ('estado', models.CharField(choices=[('Aprobada', 'Aprobada'), ('Denegada', 'Denegada'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudesBackupview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Solicitudes_backupview',
                'managed': False,
            },
        ),
    ]
