# Generated by Django 4.0.1 on 2022-04-17 23:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0003_remove_user_rol'),
        ('Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(choices=[('DIRECTOR_COMEX', 'Director COMEX'), ('DIRECTOR_DESARROLLO', 'Director Desarrollo'), ('ESPECIALISTA_COMEX', 'Especialista COMEX'), ('ESPECIALISTA_MARKETING', 'Especialista Marketing'), ('SUPERVISOR', 'Supervisor'), ('CONSULTOR', 'Consultor')], default='CONSULTOR', max_length=250, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
