# Generated by Django 4.0.1 on 2022-02-06 13:39

import Solicitudes.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, validators=[Solicitudes.models.validate_cantidad]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fechasol',
            field=models.DateField(default=datetime.date(2022, 2, 6), validators=[Solicitudes.models.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='numsolicitud',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, validators=[Solicitudes.models.validate_numsolicitud]),
        ),
    ]
