# Generated by Django 4.0.1 on 2022-02-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'managed': False, 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
