# Generated by Django 4.0.1 on 2022-03-23 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0005_alter_especialistacomex_id'),
        ('Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_producto',
            name='numcontratoproveedor',
            field=models.ForeignKey(blank=True, db_column='numcontratoproveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
    ]
