# Generated by Django 3.2.9 on 2021-12-13 09:28

import Solicitudes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('numsolicitud', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[Solicitudes.models.validate_numsolicitud])),
                ('cantidad', models.IntegerField(validators=[Solicitudes.models.validate_cantidad])),
                ('fechasol', models.DateField()),
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.producto')),
                ('numcontratocliente', models.ForeignKey(db_column='numcontratocliente', on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.cliente')),
                ('numcontratoproveedor', models.ForeignKey(blank=True, db_column='numcontratoproveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.proveedor')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'managed': True,
                'unique_together': {('numsolicitud', 'numcontratocliente', 'idproducto')},
            },
        ),
    ]
