# Generated by Django 4.0.1 on 2022-02-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0002_alter_proveedor_options'),
        ('Solicitudes', '0002_alter_solicitud_cantidad_alter_solicitud_fechasol_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Almacen',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numcontratocliente',
        ),
        migrations.DeleteModel(
            name='FacturaCliente',
        ),
        migrations.DeleteModel(
            name='FacturaProveedor',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='numcontratoproveedor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='idproducto',
            field=models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.producto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='numcontratocliente',
            field=models.ForeignKey(db_column='numcontratocliente', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='numcontratoproveedor',
            field=models.ForeignKey(blank=True, db_column='numcontratoproveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.proveedor'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ContratoCliente',
        ),
        migrations.DeleteModel(
            name='ContratoProveedor',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
