# Generated by Django 4.0.1 on 2022-03-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0002_solicitud_producto_numcontratoproveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'managed': False, 'ordering': ['numsolicitud', 'fechasol'], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
