# Generated by Django 3.2.9 on 2021-11-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0003_alter_registrocontrolsolicitud_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocontrolsolicitud',
            options={'managed': False, 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
