# Generated by Django 4.0.1 on 2022-02-10 16:41

import Solicitudes.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0003_alter_solicitud_fechasol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fechasol',
            field=models.DateField(default=datetime.date(2022, 2, 10), validators=[Solicitudes.models.validate_fecha]),
        ),
    ]
