# Generated by Django 4.0.1 on 2022-04-24 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0006_alter_solicitud_bateria_fechasol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria',
            name='fechasol',
            field=models.DateField(default=datetime.date(2022, 4, 24), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo',
            name='fechasol',
            field=models.DateField(default=datetime.date(2022, 4, 24), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico',
            name='fechasol',
            field=models.DateField(default=datetime.date(2022, 4, 24), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa',
            name='fechasol',
            field=models.DateField(default=datetime.date(2022, 4, 24), verbose_name='Fecha'),
        ),
        migrations.AlterModelTable(
            name='solicitud_bateria_proveedor',
            table='solicitud_bateria_proveedor',
        ),
        migrations.AlterModelTable(
            name='solicitud_equipo_proveedor',
            table='solicitud_equipo_proveedor',
        ),
        migrations.AlterModelTable(
            name='solicitud_neumatico_proveedor',
            table='solicitud_neumatico_proveedor',
        ),
        migrations.AlterModelTable(
            name='solicitud_ppa_proveedor',
            table='solicitud_ppa_proveedor',
        ),
    ]
