# Generated by Django 4.0.1 on 2022-06-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0016_alter_cliente_telefono_alter_ministerio_telefono_and_more'),
        ('Solicitudes', '0006_alter_solicitud_bateria_fechasol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria_proxy',
            name='idproducto',
            field=models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.bateria', verbose_name='Batería'),
        ),
    ]
