# Generated by Django 4.0.1 on 2022-06-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0017_alter_cliente_telefono_alter_ministerio_telefono_and_more'),
        ('Solicitudes', '0007_alter_solicitud_bateria_proxy_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_neumatico_proveedor',
            name='codmincex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.proveedor', verbose_name='Proveedor'),
        ),
    ]
