# Generated by Django 4.0.1 on 2022-06-28 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0008_alter_solicitud_neumatico_proveedor_codmincex'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_bateria',
            name='fecha_venc',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Caducidad la Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud_bateria',
            name='plazo',
            field=models.CharField(choices=[('3 días', '3 días'), ('7 días', '7 días')], default='3 días', max_length=15),
        ),
        migrations.AddField(
            model_name='solicitud_equipo',
            name='fecha_venc',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Caducidad la Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud_equipo',
            name='plazo',
            field=models.CharField(choices=[('3 días', '3 días'), ('7 días', '7 días')], default='3 días', max_length=15),
        ),
        migrations.AddField(
            model_name='solicitud_neumatico',
            name='fecha_venc',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Caducidad la Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud_neumatico',
            name='plazo',
            field=models.CharField(choices=[('3 días', '3 días'), ('7 días', '7 días')], default='3 días', max_length=15),
        ),
        migrations.AddField(
            model_name='solicitud_ppa',
            name='fecha_venc',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Caducidad la Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud_ppa',
            name='plazo',
            field=models.CharField(choices=[('3 días', '3 días'), ('7 días', '7 días')], default='3 días', max_length=15),
        ),
    ]
