# Generated by Django 4.0.1 on 2022-05-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0007_alter_marca_codigomarca'),
        ('Solicitudes', '0008_remove_solicitud_bateria_idespecialista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_equipo_proveedor',
            name='codmincex',
            field=models.ForeignKey(db_column='codmincex', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.proveedor', unique=True, verbose_name='Proveedor'),
        ),
    ]
