# Generated by Django 4.0.1 on 2022-06-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0009_solicitud_bateria_fecha_venc_solicitud_bateria_plazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria',
            name='fecha_venc',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Caducidad la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo',
            name='fecha_venc',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Caducidad la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico',
            name='fecha_venc',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Caducidad la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa',
            name='fecha_venc',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Caducidad la Solicitud'),
        ),
    ]
