# Generated by Django 4.0.1 on 2022-04-28 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0005_alter_oferta_equipo_fecha'),
        ('Solicitudes', '0009_remove_solicitud_bateria_idespecialista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_bateria',
            name='idespecialista',
            field=models.ForeignKey(db_column='idespecialista', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex', verbose_name='Especialista COMEX'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_equipo',
            name='idespecialista',
            field=models.ForeignKey(db_column='idespecialista', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex', verbose_name='Especialista COMEX'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_neumatico',
            name='idespecialista',
            field=models.ForeignKey(db_column='idespecialista', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex', verbose_name='Especialista COMEX'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_ppa',
            name='idespecialista',
            field=models.ForeignKey(db_column='idespecialista', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex', verbose_name='Especialista COMEX'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud_bateria',
            name='fechasol',
            field=models.DateField(default=datetime.date(2022, 4, 28), verbose_name='Fecha de la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo',
            name='fechasol',
            field=models.DateField(default=datetime.date(2022, 4, 28), verbose_name='Fecha de la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico',
            name='fechasol',
            field=models.DateField(default=datetime.date(2022, 4, 28), verbose_name='Fecha de la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa',
            name='fechasol',
            field=models.DateField(default=datetime.date(2022, 4, 28), verbose_name='Fecha de la Solicitud'),
        ),
    ]
