# Generated by Django 4.0.1 on 2022-04-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COMEX', '0005_alter_oferta_equipo_fecha'),
        ('Solicitudes', '0010_solicitud_bateria_idespecialista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria',
            name='idespecialista',
            field=models.ForeignKey(blank=True, db_column='idespecialista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex', verbose_name='Especialista COMEX'),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo',
            name='idespecialista',
            field=models.ForeignKey(blank=True, db_column='idespecialista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex', verbose_name='Especialista COMEX'),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico',
            name='idespecialista',
            field=models.ForeignKey(blank=True, db_column='idespecialista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex', verbose_name='Especialista COMEX'),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa',
            name='idespecialista',
            field=models.ForeignKey(blank=True, db_column='idespecialista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='COMEX.especialistacomex', verbose_name='Especialista COMEX'),
        ),
    ]
