# Generated by Django 4.0.1 on 2022-05-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0007_alter_marca_codigomarca'),
        ('Solicitudes', '0011_alter_solicitud_bateria_fechasol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_neumatico_proxy',
            name='idproducto',
            field=models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.neumatico', unique=True, verbose_name='Neumático'),
        ),
    ]
