# Generated by Django 4.0.1 on 2022-05-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0007_alter_marca_codigomarca'),
        ('Solicitudes', '0012_alter_solicitud_neumatico_proxy_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_neumatico_proveedor',
            name='codmincex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.proveedor', unique=True, verbose_name='Proveedor'),
        ),
    ]
