# Generated by Django 4.0.1 on 2022-05-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0007_alter_marca_codigomarca'),
        ('Solicitudes', '0013_alter_solicitud_neumatico_proveedor_codmincex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria_proveedor',
            name='codmincex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.proveedor', unique=True, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='solicitud_bateria_proxy',
            name='idproducto',
            field=models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.bateria', unique=True, verbose_name='Batería'),
        ),
    ]
