# Generated by Django 4.0.1 on 2022-05-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0014_alter_solicitud_bateria_proveedor_codmincex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria',
            name='valor_estimado',
            field=models.FloatField(verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo',
            name='valor_estimado',
            field=models.FloatField(verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico',
            name='valor_estimado',
            field=models.FloatField(verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa',
            name='valor_estimado',
            field=models.FloatField(verbose_name='Valor Estimado'),
        ),
    ]
