# Generated by Django 4.0.1 on 2022-05-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0015_alter_solicitud_bateria_valor_estimado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_ppa',
            name='equipo',
        ),
    ]
