# Generated by Django 4.0.1 on 2022-05-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0027_alter_pais_nompais_alter_provincia_capital_and_more'),
        ('Solicitudes', '0024_alter_solicitud_bateria_fechasol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria',
            name='numcontratocliente',
            field=models.ForeignKey(db_column='numcontratocliente', default='Seleccione', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud_bateria',
            name='observaciones',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo',
            name='numcontratocliente',
            field=models.ForeignKey(db_column='numcontratocliente', default='Seleccione', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo',
            name='observaciones',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico',
            name='numcontratocliente',
            field=models.ForeignKey(db_column='numcontratocliente', default='Seleccione', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico',
            name='observaciones',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa',
            name='numcontratocliente',
            field=models.ForeignKey(db_column='numcontratocliente', default='Seleccione', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa',
            name='observaciones',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones'),
        ),
    ]
