# Generated by Django 4.0.1 on 2022-05-26 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0043_alter_pais_nompais_alter_provincia_capital_and_more'),
        ('Solicitudes', '0029_alter_solicitud_bateria_fechasol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_neumatico_proxy',
            name='idproducto',
            field=models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.neumatico', verbose_name='Neumático'),
        ),
    ]
