# Generated by Django 4.0.1 on 2022-05-26 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0031_alter_solicitud_bateria_proveedor_codmincex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria_proxy',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo_proxy',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico_proxy',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa_proxy',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
