# Generated by Django 4.0.1 on 2022-05-26 07:31

import Solicitudes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0032_alter_solicitud_bateria_proxy_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria_proxy',
            name='cantidad',
            field=models.IntegerField(validators=[Solicitudes.models.validate_cantidad]),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo_proxy',
            name='cantidad',
            field=models.IntegerField(validators=[Solicitudes.models.validate_cantidad]),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico_proxy',
            name='cantidad',
            field=models.IntegerField(validators=[Solicitudes.models.validate_cantidad]),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa_proxy',
            name='cantidad',
            field=models.IntegerField(validators=[Solicitudes.models.validate_cantidad]),
        ),
    ]
