# Generated by Django 4.0.1 on 2022-05-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0033_alter_solicitud_bateria_proxy_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_bateria',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='solicitud_equipo',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='solicitud_neumatico',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='solicitud_ppa',
            name='proveedores',
        ),
    ]
