# Generated by Django 4.0.1 on 2022-05-26 18:17

import Solicitudes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0050_alter_cliente_telefono_alter_ministerio_telefono_and_more'),
        ('Solicitudes', '0034_remove_solicitud_bateria_proveedores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria',
            name='numcontratocliente',
            field=models.ForeignKey(db_column='numcontratocliente', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud_bateria',
            name='valor_estimado',
            field=models.FloatField(validators=[Solicitudes.models.validate_valor_estimado], verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo',
            name='numcontratocliente',
            field=models.ForeignKey(db_column='numcontratocliente', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo',
            name='valor_estimado',
            field=models.FloatField(validators=[Solicitudes.models.validate_valor_estimado], verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico',
            name='numcontratocliente',
            field=models.ForeignKey(db_column='numcontratocliente', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico',
            name='valor_estimado',
            field=models.FloatField(validators=[Solicitudes.models.validate_valor_estimado], verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa',
            name='numcontratocliente',
            field=models.ForeignKey(db_column='numcontratocliente', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa',
            name='valor_estimado',
            field=models.FloatField(validators=[Solicitudes.models.validate_valor_estimado], verbose_name='Valor Estimado'),
        ),
    ]
