# Generated by Django 4.0.1 on 2022-05-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0053_alter_cliente_telefono_alter_ministerio_telefono_and_more'),
        ('Solicitudes', '0035_alter_solicitud_bateria_numcontratocliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_bateria',
            name='numcontratocliente',
        ),
        migrations.RemoveField(
            model_name='solicitud_equipo',
            name='numcontratocliente',
        ),
        migrations.RemoveField(
            model_name='solicitud_neumatico',
            name='numcontratocliente',
        ),
        migrations.RemoveField(
            model_name='solicitud_ppa',
            name='numcontratocliente',
        ),
        migrations.AddField(
            model_name='solicitud_bateria',
            name='cliente',
            field=models.ForeignKey(db_column='reeup', default='126.0.04878', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_equipo',
            name='cliente',
            field=models.ForeignKey(db_column='reeup', default='126.0.04878', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_neumatico',
            name='cliente',
            field=models.ForeignKey(db_column='reeup', default='126.0.04878', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud_ppa',
            name='cliente',
            field=models.ForeignKey(db_column='reeup', default='126.0.04878', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
