# Generated by Django 4.0.1 on 2022-05-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0062_alter_cliente_telefono_alter_ministerio_telefono_and_more'),
        ('Solicitudes', '0037_alter_solicitud_bateria_fechasol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_bateria',
            name='proveedores',
            field=models.ManyToManyField(through='Solicitudes.Solicitud_Bateria_Proveedor', to='Nomencladores.Proveedor', verbose_name='Proveedores'),
        ),
        migrations.AddField(
            model_name='solicitud_equipo',
            name='proveedores',
            field=models.ManyToManyField(related_name='Proveedores', through='Solicitudes.Solicitud_Equipo_Proveedor', to='Nomencladores.Proveedor'),
        ),
        migrations.AddField(
            model_name='solicitud_neumatico',
            name='proveedores',
            field=models.ManyToManyField(through='Solicitudes.Solicitud_Neumatico_Proveedor', to='Nomencladores.Proveedor', verbose_name='Proveedores'),
        ),
        migrations.AddField(
            model_name='solicitud_ppa',
            name='proveedores',
            field=models.ManyToManyField(through='Solicitudes.Solicitud_PPA_Proveedor', to='Nomencladores.Proveedor', verbose_name='Proveedores'),
        ),
    ]
