# Generated by Django 4.0.1 on 2022-06-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0042_alter_solicitud_bateria_fechasol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_equipo_proxy',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
