# Generated by Django 4.0.1 on 2022-06-07 08:02

import Solicitudes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0043_alter_solicitud_equipo_proxy_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_bateria_proxy',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[Solicitudes.models.validate_cantidad]),
        ),
        migrations.AlterField(
            model_name='solicitud_equipo_proxy',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[Solicitudes.models.validate_cantidad]),
        ),
        migrations.AlterField(
            model_name='solicitud_neumatico_proxy',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[Solicitudes.models.validate_cantidad]),
        ),
        migrations.AlterField(
            model_name='solicitud_ppa_proxy',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[Solicitudes.models.validate_cantidad]),
        ),
    ]
