# Generated by Django 4.0.1 on 2022-04-07 17:27

import Nomencladores.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('idalmacen', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipoalmacen', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('numcontratocliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de Contrato')),
                ('nomcliente', models.CharField(max_length=100, validators=[Nomencladores.validators.UnicodenameValidator()], verbose_name='Nombre')),
                ('OSDE', models.CharField(max_length=45, validators=[Nomencladores.validators.UnicodenameValidator()])),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('pais', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Casa_Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(max_length=60, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Eléctronico')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('contacto', models.TextField(verbose_name='Persona de Contacto')),
                ('sitio_web', models.TextField(verbose_name='Página Web')),
            ],
            options={
                'verbose_name': 'Casa Matriz',
                'db_table': 'casa_matriz',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nombreproducto', models.CharField(max_length=50, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('PZ', 'PPA'), ('EQ', 'Equipo'), ('Batería', 'Batería'), ('Neumático', 'Neumático')], default='PZ', max_length=10)),
                ('UM', models.CharField(choices=[('U', 'U'), ('SET', 'SET')], default='U', max_length=5)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codmincex', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeCodeValidator], verbose_name='Código MINCEX')),
                ('nomproveedor', models.CharField(max_length=45, validators=[Nomencladores.validators.UnicodenameValidator()], verbose_name='Nombre')),
                ('clasificacion', models.TextField(choices=[('Productor', 'Productor'), ('Comercializador', 'Comercializador')], default='Productor', verbose_name='Clasificación')),
                ('idpais', models.ForeignKey(db_column='idpais', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigoprovincia', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sucursal_Cuba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(max_length=60, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Eléctronico')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('contacto', models.TextField(verbose_name='Persona de Contacto')),
                ('carnet_trabajo', models.TextField(verbose_name='Carnet de Trabajo')),
                ('proveedor', models.ForeignKey(db_column='codmincex', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.proveedor', verbose_name='Sucursal en Cuba')),
            ],
            options={
                'verbose_name': 'Sucursal en Cuba',
                'db_table': 'sucursal_cuba',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codmincex', models.ForeignKey(db_column='codmincex', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.proveedor', verbose_name='Proveedores')),
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.producto', verbose_name='Productos')),
            ],
            options={
                'db_table': 'proveedor_producto',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='productos',
            field=models.ManyToManyField(db_column='idproducto', through='Nomencladores.Proveedor_Producto', to='Nomencladores.Producto', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('codmincex', 'idpais')},
        ),
    ]
