# Generated by Django 4.0.1 on 2022-04-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EspecialistaCOMEX',
        ),
    ]
