# Generated by Django 4.0.1 on 2022-04-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor_Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sucursal_cuba',
            field=models.ManyToManyField(through='Nomencladores.Proveedor_Sucursal', to='Nomencladores.Sucursal_Cuba'),
        ),
        migrations.AddField(
            model_name='proveedor_sucursal',
            name='codmincex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor_sucursal',
            name='identificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.sucursal_cuba'),
        ),
    ]
