# Generated by Django 4.0.1 on 2022-02-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
