# Generated by Django 4.0.1 on 2022-04-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa_matriz',
            name='proveedor',
            field=models.ForeignKey(db_column='codmincex', default=1, on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.proveedor', verbose_name='Casa Matriz'),
            preserve_default=False,
        ),
    ]
