# Generated by Django 4.0.1 on 2022-04-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincia',
            old_name='codigoprovincia',
            new_name='id',
        ),
    ]
