# Generated by Django 4.0.1 on 2022-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='codigoprovincia',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Abreviatura'),
        ),
    ]
