# Generated by Django 4.0.1 on 2022-04-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0002_alter_cliente_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(db_column='codigoprovincia', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.provincia', verbose_name='Provincia'),
        ),
    ]
