# Generated by Django 4.0.1 on 2022-03-21 17:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nomencladores', '0002_rename_usuario_especialistacomex_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='especialistacomex',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='especialistacomex',
            name='idespecialista',
        ),
        migrations.RemoveField(
            model_name='especialistacomex',
            name='username',
        ),
        migrations.AddField(
            model_name='especialistacomex',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=65, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
