# Generated by Django 4.0.1 on 2022-04-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0002_delete_especialistacomex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincia',
            old_name='idprovincia',
            new_name='codigoprovincia',
        ),
    ]
