# Generated by Django 4.0.1 on 2022-02-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0003_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratocliente',
            options={'managed': False, 'verbose_name': 'Contrato de Cliente', 'verbose_name_plural': 'Contratos de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contratoproveedor',
            options={'managed': False, 'verbose_name': 'Contrato de Proveedor', 'verbose_name_plural': 'Contratos de Proveedores'},
        ),
    ]
