# Generated by Django 4.0.1 on 2022-03-21 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nomencladores', '0003_alter_especialistacomex_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='especialistacomex',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='especialistacomex',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='especialistacomex',
            name='id',
            field=models.ForeignKey(db_column='id', default=65, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
