# Generated by Django 4.0.1 on 2022-04-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0003_alter_pais_nompais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='id',
            field=models.IntegerField(default=1),
        ),
    ]
