# Generated by Django 4.0.1 on 2022-04-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0003_rename_id_provincia_codigoprovincia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='numpais',
            new_name='id',
        ),
    ]
