# Generated by Django 4.0.1 on 2022-02-17 03:24

import Nomencladores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0004_alter_contratocliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idproducto',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreproducto',
            field=models.CharField(max_length=50, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Descripción'),
        ),
    ]
