# Generated by Django 4.0.1 on 2022-04-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0004_pais_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='id',
        ),
    ]
