# Generated by Django 4.0.1 on 2022-03-21 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nomencladores', '0004_alter_especialistacomex_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistacomex',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
