# Generated by Django 4.0.1 on 2022-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0004_rename_provincia_cliente_codigoprovincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numcontratocliente',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Numero de Contrato'),
        ),
    ]
