# Generated by Django 4.0.1 on 2022-03-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0005_alter_especialistacomex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='productos',
            field=models.ManyToManyField(through='Nomencladores.Proveedor_Producto', to='Nomencladores.Producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='idprovincia',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
