# Generated by Django 4.0.1 on 2022-04-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0005_remove_pais_codigopais_alter_pais_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
