# Generated by Django 4.0.1 on 2022-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0005_alter_cliente_numcontratocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numcontratocliente',
            field=models.BigIntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='Numero de Contrato'),
        ),
    ]
