# Generated by Django 4.0.1 on 2022-04-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0005_remove_pais_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='codigopais',
            new_name='id',
        ),
    ]
