# Generated by Django 4.0.1 on 2022-05-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0006_alter_cliente_numcontratocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='codigomarca',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
