# Generated by Django 4.0.1 on 2022-03-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0006_alter_proveedor_productos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialistacomex',
            old_name='id',
            new_name='idespecialista',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='productos',
            field=models.ManyToManyField(db_column='idproducto', through='Nomencladores.Proveedor_Producto', to='Nomencladores.Producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='idprovincia',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Código'),
        ),
    ]
