# Generated by Django 4.0.1 on 2022-04-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0007_remove_pais_id_pais_codigopais'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppa',
            name='equipo',
            field=models.ForeignKey(db_column='modelo', default=1, on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.equipo'),
            preserve_default=False,
        ),
    ]
