# Generated by Django 4.0.1 on 2022-03-25 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0007_rename_id_especialistacomex_idespecialista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincia',
            old_name='idprovincia',
            new_name='codprovincia',
        ),
    ]
