# Generated by Django 4.0.1 on 2022-05-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0007_alter_marca_codigomarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numcontratocliente',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Numero de Contrato'),
        ),
    ]
