# Generated by Django 4.0.1 on 2022-04-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0008_ppa_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppa',
            old_name='equipo',
            new_name='modelo',
        ),
    ]
