# Generated by Django 4.0.1 on 2022-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0008_alter_cliente_numcontratocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nommarca',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
    ]
