# Generated by Django 4.0.1 on 2022-03-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0008_rename_idprovincia_provincia_codprovincia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincia',
            old_name='codprovincia',
            new_name='id',
        ),
    ]
