# Generated by Django 4.0.1 on 2022-04-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0009_rename_equipo_ppa_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codigomarca', models.IntegerField(max_length=5, primary_key=True, serialize=False, verbose_name='Código')),
                ('nommarca', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='bateria',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.marca', verbose_name='Marca'),
        ),
    ]
