# Generated by Django 4.0.1 on 2022-05-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0009_alter_marca_nommarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='productos',
            field=models.CharField(choices=[('Equipos', 'Equipos'), ('PPAS', 'PPAS'), ('Neumáticos', 'Neumáticos'), ('Baterías', 'Baterías')], default='Equipos', max_length=15, verbose_name='Tipos de Productos'),
        ),
    ]
