# Generated by Django 4.0.1 on 2022-04-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0010_marca_alter_bateria_marca_alter_equipo_marca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'managed': True, 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelTable(
            name='marca',
            table='marca',
        ),
    ]
