# Generated by Django 4.0.1 on 2022-03-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0010_rename_id_provincia_idprovincia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='idprovincia',
            new_name='id',
        ),
    ]
