# Generated by Django 4.0.1 on 2022-04-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0011_alter_marca_options_alter_marca_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincia',
            old_name='codigoprovincia',
            new_name='id',
        ),
    ]
