# Generated by Django 4.0.1 on 2022-05-21 10:59

import Nomencladores.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0011_remove_marca_productos_marca_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('reeup', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeREEUPValidator], verbose_name='Código REEUP')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Nombre')),
                ('siglas', models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Siglas')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.IntegerField(max_length=8, unique=True, verbose_name='Teléfono')),
            ],
            options={
                'db_table': 'ministerio',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nomcliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numcontratocliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=1, max_length=100, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default=1, max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='reeup',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeREEUPValidator], verbose_name='Código REEUP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='siglas',
            field=models.CharField(default=1, max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Siglas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(default=1, max_length=8, unique=True, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bateria',
            name='marca',
            field=models.ForeignKey(db_column='codigomarca', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(db_column='codigomarca', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='marca',
            field=models.ForeignKey(db_column='codigomarca', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='marca',
            field=models.ForeignKey(db_column='codigomarca', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.marca', verbose_name='Marca'),
        ),
        migrations.CreateModel(
            name='OSDE',
            fields=[
                ('reeup', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeREEUPValidator], verbose_name='Código REEUP')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Nombre')),
                ('siglas', models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Siglas')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.IntegerField(max_length=8, unique=True, verbose_name='Teléfono')),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.ministerio', verbose_name='Ministerio')),
            ],
            options={
                'db_table': 'OSDE',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='OSDE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.osde', validators=[Nomencladores.validators.UnicodenameValidator()]),
        ),
    ]
