# Generated by Django 4.0.1 on 2022-05-21 11:46

import Nomencladores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0012_ministerio_remove_cliente_nomcliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministerio',
            options={'managed': True, 'verbose_name': 'Ministerio', 'verbose_name_plural': 'Ministerios'},
        ),
        migrations.AlterModelOptions(
            name='osde',
            options={'managed': True, 'verbose_name': 'OSDE', 'verbose_name_plural': 'OSDE'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='reeup',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeREEUPValidator], verbose_name='Código REEUP'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='reeup',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeREEUPValidator], verbose_name='Código REEUP'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='reeup',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeREEUPValidator], verbose_name='Código REEUP'),
        ),
    ]
