# Generated by Django 4.0.1 on 2022-04-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0012_rename_codigoprovincia_provincia_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincia',
            old_name='id',
            new_name='codigoprovincia',
        ),
    ]
