# Generated by Django 4.0.1 on 2022-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0012_cliente_idprovincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistacomex',
            name='categoria',
            field=models.CharField(choices=[('PZ', 'Partes, Piezas y Accesorios'), ('EQ', 'Equipo')], default='PZ', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('PZ', 'Partes, Piezas y Accesorios'), ('EQ', 'Equipo'), ('Batería', 'Batería'), ('Neumático', 'Neumático')], default='PZ', max_length=10),
        ),
    ]
