# Generated by Django 4.0.1 on 2022-05-21 15:35

import Nomencladores.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0013_alter_ministerio_options_alter_osde_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='OSDE',
            field=models.ForeignKey(db_column='OSDE.reeup', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.osde', validators=[Nomencladores.validators.UnicodenameValidator()]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigoprovincia',
            field=models.ForeignKey(db_column='codigoprovincia', default='HB', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.provincia', verbose_name='Provincia'),
        ),
    ]
