# Generated by Django 4.0.1 on 2022-04-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0013_rename_id_provincia_codigoprovincia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppa',
            old_name='modelo',
            new_name='equipo',
        ),
    ]
