# Generated by Django 4.0.1 on 2022-03-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0014_rename_id_cliente_idprovincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idprovincia',
            field=models.ForeignKey(db_column='idprovincia', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.provincia', verbose_name='Provincia'),
        ),
    ]
