# Generated by Django 4.0.1 on 2022-04-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0014_rename_modelo_ppa_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa_matriz',
            options={'managed': True, 'verbose_name': 'Casa Matriz', 'verbose_name_plural': 'Casa Matriz'},
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigopais',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
