# Generated by Django 4.0.1 on 2022-05-21 15:40

import Nomencladores.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0014_alter_cliente_osde_alter_cliente_codigoprovincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='OSDE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.osde', validators=[Nomencladores.validators.UnicodenameValidator()]),
        ),
    ]
