# Generated by Django 4.0.1 on 2022-04-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0015_alter_casa_matriz_options_alter_pais_codigopais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='codigopais',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
