# Generated by Django 4.0.1 on 2022-05-21 15:44

import Nomencladores.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0015_alter_cliente_osde'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='representante',
            field=models.CharField(default=1, max_length=40, validators=[Nomencladores.validators.UnicodenameValidator()], verbose_name='Representante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='OSDE',
            field=models.ForeignKey(default='GEDIC', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.osde', validators=[Nomencladores.validators.UnicodenameValidator()]),
        ),
    ]
