# Generated by Django 4.0.1 on 2022-04-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0016_alter_pais_codigopais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nompais',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
