# Generated by Django 4.0.1 on 2022-05-22 07:58

import Nomencladores.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0017_alter_cliente_osde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='OSDE',
            field=models.ForeignKey(db_column='OSDE.reeup', default='GEDIC', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.osde', validators=[Nomencladores.validators.UnicodenameValidator()]),
        ),
    ]
