# Generated by Django 4.0.1 on 2022-04-21 22:33

import Nomencladores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0017_alter_pais_nompais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nomproveedor',
            field=models.CharField(max_length=100, validators=[Nomencladores.validators.UnicodenameValidator()], verbose_name='Nombre'),
        ),
    ]
