# Generated by Django 4.0.1 on 2022-04-21 22:33

import Nomencladores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0018_alter_proveedor_nomproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='codmincex',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeCodeValidator], verbose_name='Código MINCEX'),
        ),
    ]
