# Generated by Django 4.0.1 on 2022-04-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0019_alter_proveedor_codmincex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bateria',
            name='idproducto',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='idproducto',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='idproducto',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='idproducto',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
