# Generated by Django 4.0.1 on 2022-05-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0020_alter_cliente_osde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='OSDE',
        ),
    ]
