# Generated by Django 4.0.1 on 2022-05-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0021_remove_cliente_osde'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='OSDE',
            field=models.ForeignKey(default='GEDIC', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.osde'),
        ),
    ]
