# Generated by Django 4.0.1 on 2022-05-22 08:06

import Nomencladores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0022_cliente_osde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='reeup',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeREEUPValidator], verbose_name='Código REEUP'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='reeup',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeREEUPValidator], verbose_name='Código REEUP'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='reeup',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[Nomencladores.validators.UnicodeREEUPValidator], verbose_name='Código REEUP'),
        ),
    ]
