# Generated by Django 4.0.1 on 2022-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0024_remove_ppa_equipo_ppa_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='codigomarca',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
