# Generated by Django 4.0.1 on 2022-05-22 11:09

import Nomencladores.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0024_um_alter_cliente_nombre_alter_cliente_reeup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bateria',
            name='UM',
            field=models.ForeignKey(db_column='codigoum', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.um'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='UM',
            field=models.ForeignKey(db_column='codigoum', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.um'),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='UM',
            field=models.ForeignKey(db_column='codigoum', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.um'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nompais',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='UM',
            field=models.ForeignKey(db_column='codigoum', on_delete=django.db.models.deletion.DO_NOTHING, to='Nomencladores.um'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='capital',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigoprovincia',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[Nomencladores.models.nombre_validator], verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
    ]
