# Generated by Django 4.0.1 on 2022-05-22 17:48

import Nomencladores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0025_alter_bateria_um_alter_equipo_um_alter_neumatico_um_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nompais',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='capital',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigoprovincia',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[Nomencladores.models.nombre_validator], verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
        migrations.AlterField(
            model_name='um',
            name='codigoum',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, validators=[Nomencladores.models.codigo_validator], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='um',
            name='descripcionum',
            field=models.CharField(max_length=10, unique=True, validators=[Nomencladores.models.descripcion_validator], verbose_name='Descripción'),
        ),
    ]
