# Generated by Django 4.0.1 on 2022-05-23 10:55

import Nomencladores.models
import Nomencladores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0028_alter_pais_nompais_alter_proveedor_codmincex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bateria',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nompais',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ppa',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True, validators=[Nomencladores.validators.UnicodenameValidator], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='capital',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigoprovincia',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[Nomencladores.models.nombre_validator], verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
    ]
