# Generated by Django 4.0.1 on 2022-07-06 14:50

import Nomencladores.models
import Nomencladores.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0030_remove_sucursal_cuba_carnet_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa_matriz',
            name='proveedor',
            field=models.OneToOneField(db_column='codmincex', on_delete=django.db.models.deletion.PROTECT, to='Nomencladores.proveedor', verbose_name='Casa Matriz'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='siglas',
            field=models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(unique=True, validators=[Nomencladores.models.validate_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='siglas',
            field=models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='telefono',
            field=models.IntegerField(unique=True, validators=[Nomencladores.models.validate_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='siglas',
            field=models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='telefono',
            field=models.IntegerField(unique=True, validators=[Nomencladores.models.validate_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nompais',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='capital',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigoprovincia',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[Nomencladores.models.nombre_validator], verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
    ]
