# Generated by Django 4.0.1 on 2022-07-06 17:08

import Nomencladores.models
import Nomencladores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0038_alter_cliente_nombre_alter_cliente_siglas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='siglas',
            field=models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=8, unique=True, validators=[Nomencladores.validators.TelefonoValidator.telefono_validator], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='siglas',
            field=models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='telefono',
            field=models.CharField(max_length=8, unique=True, validators=[Nomencladores.validators.TelefonoValidator.telefono_validator], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='siglas',
            field=models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='telefono',
            field=models.CharField(max_length=8, unique=True, validators=[Nomencladores.validators.TelefonoValidator.telefono_validator], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nompais',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='capital',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigoprovincia',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[Nomencladores.models.nombre_validator], verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
    ]
