# Generated by Django 4.0.1 on 2022-07-06 19:12

import Nomencladores.models
import Nomencladores.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0043_alter_cliente_nombre_alter_cliente_siglas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='fecha_caducidad',
            field=models.DateTimeField(blank=True, default=Nomencladores.models.fecha_caducidad_proveedor, null=True, verbose_name='Caducidad del Contrato'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_contrato',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[Nomencladores.models.fecha_contrato]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_contrato',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[Nomencladores.models.fecha_contrato]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='siglas',
            field=models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='siglas',
            field=models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='osde',
            name='siglas',
            field=models.CharField(max_length=15, unique=True, validators=[Nomencladores.validators.UnicodenameValidator, Nomencladores.models.nombre_validator], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nompais',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='capital',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigoprovincia',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[Nomencladores.models.nombre_validator], verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, validators=[Nomencladores.models.nombre_validator]),
        ),
    ]
