# Generated by Django 3.2.7 on 2021-11-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomencladores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GestorCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='Introduzca la dirección IP.', max_length=15)),
                ('nombre', models.CharField(help_text='Introduzca el nombre.', max_length=10)),
                ('tarjeta_red', models.CharField(help_text='Introduzca la tarjeta de red.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SitioWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=15)),
                ('host', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escriba el nombre.', max_length=20)),
                ('apellido', models.CharField(help_text='Escriba los apellidos.', max_length=40)),
                ('correo', models.EmailField(help_text='Escriba la dirección de correo electrónico.', max_length=254)),
                ('telefono', models.CharField(help_text='Escriba el número telefónico.', max_length=8)),
                ('nombre_usuario', models.CharField(help_text='Escriba el nombre de usuario.', max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('E', 'Empleado'), ('A', 'Directorio Activo'), ('T', 'Adiestrado')], help_text='Escoja su tipo de usuario.', max_length=1)),
                ('cargo', models.CharField(choices=[('D', 'Jefe de Departamento'), ('P', 'Jefe de Proyecto'), ('E', 'Especialista'), ('T', 'Técnico')], help_text='Escoja su cargo.', max_length=1)),
                ('dominio', models.ForeignKey(help_text='Escoja el dominio.', on_delete=django.db.models.deletion.PROTECT, to='nomencladores.dominio')),
                ('entidad', models.ForeignKey(help_text='Escoja la entidad.', on_delete=django.db.models.deletion.PROTECT, to='nomencladores.entidad')),
                ('municipio', models.ForeignKey(help_text='Escoja el municipio.', on_delete=django.db.models.deletion.PROTECT, to='nomencladores.municipio')),
                ('pc', models.OneToOneField(help_text='Escriba el nombre de su PC.', on_delete=django.db.models.deletion.PROTECT, to='musi.pc')),
                ('provincia', models.ForeignKey(help_text='Escoja la provincia.', on_delete=django.db.models.deletion.PROTECT, to='nomencladores.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='TraficoInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('bytes_recibidos', models.FloatField()),
                ('bytes_enviados', models.FloatField()),
                ('tipo_mime', models.CharField(max_length=10)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musi.pc')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.protocolo')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.puerto')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.servidor')),
                ('sitio_web', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musi.sitioweb')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musi.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TraficoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('asunto', models.CharField(max_length=20)),
                ('cant_destino', models.IntegerField()),
                ('tamagno', models.FloatField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musi.evento')),
                ('gestor_correo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musi.gestorcorreo')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musi.pc')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.servidor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musi.usuario')),
            ],
        ),
    ]
