# Generated by Django 3.2.7 on 2021-11-23 21:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('musi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='ip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitioweb',
            name='host',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitioweb',
            name='ip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
