# Generated by Django 3.2.7 on 2021-12-01 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0004_auto_20211201_1744'),
        ('musi', '0002_auto_20211123_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pc',
            name='tarjeta_red',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.dominio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.entidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.municipio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='musi.pc'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.provincia'),
        ),
    ]
