# Generated by Django 3.2.7 on 2021-12-06 20:19

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0005_auto_20211201_1752'),
        ('musi', '0003_auto_20211201_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dominio',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.municipio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=10),
        ),
    ]
