# Generated by Django 4.0.1 on 2022-04-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tect',
            new_name='text',
        ),
    ]
